name: latent-lang-diff
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - autopep8=1.6.0=pyhd3eb1b0_1
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1t=h7f8727e_0
  - pycodestyle=2.10.0=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - absl-py==1.2.0
    - accelerate==0.21.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - bert-score==0.3.13
    - blis==0.7.9
    - cachetools==5.2.0
    - catalogue==2.0.8
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.6
    - confection==0.0.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - cymem==2.0.7
    - datasets==2.5.1
    - diffusers==0.3.0
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - einops==0.4.1
    - ema-pytorch==0.0.10
    - en-core-web-sm==3.4.1
    - evaluate==0.2.2
    - faiss-cpu==1.7.2
    - filelock==3.8.0
    - fonttools==4.38.0
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.11.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - huggingface-hub==0.14.1
    - idna==3.4
    - importlib-metadata==4.12.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lxml==4.9.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - mauve-text==0.3.0
    - modelcards==0.1.6
    - multidict==6.0.2
    - multiprocess==0.70.13
    - murmurhash==1.0.9
    - nltk==3.7
    - numpy==1.23.3
    - oauthlib==3.2.1
    - packaging==21.3
    - pandas==1.5.0
    - pathtools==0.1.2
    - pathy==0.6.2
    - pillow==9.2.0
    - pip==22.3
    - portalocker==2.7.0
    - preshed==3.0.8
    - promise==2.3
    - protobuf==3.19.5
    - psutil==5.9.2
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - regex==2022.9.13
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.1.2
    - rsa==4.9
    - sacrebleu==2.3.1
    - scikit-learn==1.1.3
    - scipy==1.9.1
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - setuptools==65.5.0
    - shortuuid==1.0.9
    - six==1.16.0
    - sklearn==0.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - spacy==3.4.2
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.5
    - tabulate==0.9.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - thinc==8.1.5
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchvision==0.13.1+cu113
    - tqdm==4.64.1
    - transformers==4.28.1
    - typer==0.4.2
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wandb==0.13.4
    - wasabi==0.10.1
    - werkzeug==2.2.2
    - wheel==0.38.1
    - x-transformers==1.1.0
    - xxhash==3.0.0
    - yarl==1.8.1
    - zipp==3.8.1
